/*     */ package org.apache.poi.hssf.record.chart;
/*     */ 
/*     */ import org.apache.poi.hssf.record.RecordInputStream;
/*     */ import org.apache.poi.hssf.record.StandardRecord;
/*     */ import org.apache.poi.util.BitField;
/*     */ import org.apache.poi.util.BitFieldFactory;
/*     */ import org.apache.poi.util.HexDump;
/*     */ import org.apache.poi.util.LittleEndianOutput;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public final class TextRecord
/*     */   extends StandardRecord
/*     */ {
/*     */   public static final short sid = 4133;
/*  33 */   private static final BitField dataLabelPlacement = BitFieldFactory.getInstance(15);
/*  34 */   private static final BitField autoColor = BitFieldFactory.getInstance(1);
/*  35 */   private static final BitField showKey = BitFieldFactory.getInstance(2);
/*  36 */   private static final BitField showValue = BitFieldFactory.getInstance(4);
/*  37 */   private static final BitField vertical = BitFieldFactory.getInstance(8);
/*  38 */   private static final BitField autoGeneratedText = BitFieldFactory.getInstance(16);
/*  39 */   private static final BitField generated = BitFieldFactory.getInstance(32);
/*  40 */   private static final BitField autoLabelDeleted = BitFieldFactory.getInstance(64);
/*  41 */   private static final BitField autoBackground = BitFieldFactory.getInstance(128);
/*  42 */   private static final BitField rotation = BitFieldFactory.getInstance(1792);
/*     */   
/*  44 */   private static final BitField showCategoryLabelAsPercentage = BitFieldFactory.getInstance(2048);
/*  45 */   private static final BitField showValueAsPercentage = BitFieldFactory.getInstance(4096);
/*  46 */   private static final BitField showBubbleSizes = BitFieldFactory.getInstance(8192);
/*  47 */   private static final BitField showLabel = BitFieldFactory.getInstance(16384);
/*     */   
/*     */   private byte field_1_horizontalAlignment;
/*     */   
/*     */   public static final byte HORIZONTAL_ALIGNMENT_LEFT = 1;
/*     */   
/*     */   public static final byte HORIZONTAL_ALIGNMENT_CENTER = 2;
/*     */   
/*     */   public static final byte HORIZONTAL_ALIGNMENT_BOTTOM = 3;
/*     */   
/*     */   public static final byte HORIZONTAL_ALIGNMENT_JUSTIFY = 4;
/*     */   
/*     */   private byte field_2_verticalAlignment;
/*     */   
/*     */   public static final byte VERTICAL_ALIGNMENT_TOP = 1;
/*     */   public static final byte VERTICAL_ALIGNMENT_CENTER = 2;
/*     */   public static final byte VERTICAL_ALIGNMENT_BOTTOM = 3;
/*     */   public static final byte VERTICAL_ALIGNMENT_JUSTIFY = 4;
/*     */   private short field_3_displayMode;
/*     */   public static final short DISPLAY_MODE_TRANSPARENT = 1;
/*     */   public static final short DISPLAY_MODE_OPAQUE = 2;
/*     */   private int field_4_rgbColor;
/*     */   private int field_5_x;
/*     */   private int field_6_y;
/*     */   private int field_7_width;
/*     */   private int field_8_height;
/*     */   private short field_9_options1;
/*     */   public static final short ROTATION_NONE = 0;
/*     */   public static final short ROTATION_TOP_TO_BOTTOM = 1;
/*     */   public static final short ROTATION_ROTATED_90_DEGREES = 2;
/*     */   public static final short ROTATION_ROTATED_90_DEGREES_CLOCKWISE = 3;
/*     */   private short field_10_indexOfColorValue;
/*     */   private short field_11_options2;
/*     */   public static final short DATA_LABEL_PLACEMENT_CHART_DEPENDENT = 0;
/*     */   public static final short DATA_LABEL_PLACEMENT_OUTSIDE = 1;
/*     */   public static final short DATA_LABEL_PLACEMENT_INSIDE = 2;
/*     */   public static final short DATA_LABEL_PLACEMENT_CENTER = 3;
/*     */   public static final short DATA_LABEL_PLACEMENT_AXIS = 4;
/*     */   public static final short DATA_LABEL_PLACEMENT_ABOVE = 5;
/*     */   public static final short DATA_LABEL_PLACEMENT_BELOW = 6;
/*     */   public static final short DATA_LABEL_PLACEMENT_LEFT = 7;
/*     */   public static final short DATA_LABEL_PLACEMENT_RIGHT = 8;
/*     */   public static final short DATA_LABEL_PLACEMENT_AUTO = 9;
/*     */   public static final short DATA_LABEL_PLACEMENT_USER_MOVED = 10;
/*     */   private short field_12_textRotation;
/*     */   
/*     */   public TextRecord() {}
/*     */   
/*     */   public TextRecord(RecordInputStream paramRecordInputStream) {
/*  96 */     this.field_1_horizontalAlignment = paramRecordInputStream.readByte();
/*  97 */     this.field_2_verticalAlignment = paramRecordInputStream.readByte();
/*  98 */     this.field_3_displayMode = paramRecordInputStream.readShort();
/*  99 */     this.field_4_rgbColor = paramRecordInputStream.readInt();
/* 100 */     this.field_5_x = paramRecordInputStream.readInt();
/* 101 */     this.field_6_y = paramRecordInputStream.readInt();
/* 102 */     this.field_7_width = paramRecordInputStream.readInt();
/* 103 */     this.field_8_height = paramRecordInputStream.readInt();
/* 104 */     this.field_9_options1 = paramRecordInputStream.readShort();
/* 105 */     this.field_10_indexOfColorValue = paramRecordInputStream.readShort();
/* 106 */     this.field_11_options2 = paramRecordInputStream.readShort();
/* 107 */     this.field_12_textRotation = paramRecordInputStream.readShort();
/*     */   }
/*     */ 
/*     */   
/*     */   public String toString() {
/* 112 */     StringBuffer stringBuffer = new StringBuffer();
/*     */     
/* 114 */     stringBuffer.append("[TEXT]\n");
/* 115 */     stringBuffer.append("    .horizontalAlignment  = ").append("0x").append(HexDump.toHex(getHorizontalAlignment())).append(" (").append(getHorizontalAlignment()).append(" )");
/*     */ 
/*     */     
/* 118 */     stringBuffer.append(System.getProperty("line.separator"));
/* 119 */     stringBuffer.append("    .verticalAlignment    = ").append("0x").append(HexDump.toHex(getVerticalAlignment())).append(" (").append(getVerticalAlignment()).append(" )");
/*     */ 
/*     */     
/* 122 */     stringBuffer.append(System.getProperty("line.separator"));
/* 123 */     stringBuffer.append("    .displayMode          = ").append("0x").append(HexDump.toHex(getDisplayMode())).append(" (").append(getDisplayMode()).append(" )");
/*     */ 
/*     */     
/* 126 */     stringBuffer.append(System.getProperty("line.separator"));
/* 127 */     stringBuffer.append("    .rgbColor             = ").append("0x").append(HexDump.toHex(getRgbColor())).append(" (").append(getRgbColor()).append(" )");
/*     */ 
/*     */     
/* 130 */     stringBuffer.append(System.getProperty("line.separator"));
/* 131 */     stringBuffer.append("    .x                    = ").append("0x").append(HexDump.toHex(getX())).append(" (").append(getX()).append(" )");
/*     */ 
/*     */     
/* 134 */     stringBuffer.append(System.getProperty("line.separator"));
/* 135 */     stringBuffer.append("    .y                    = ").append("0x").append(HexDump.toHex(getY())).append(" (").append(getY()).append(" )");
/*     */ 
/*     */     
/* 138 */     stringBuffer.append(System.getProperty("line.separator"));
/* 139 */     stringBuffer.append("    .width                = ").append("0x").append(HexDump.toHex(getWidth())).append(" (").append(getWidth()).append(" )");
/*     */ 
/*     */     
/* 142 */     stringBuffer.append(System.getProperty("line.separator"));
/* 143 */     stringBuffer.append("    .height               = ").append("0x").append(HexDump.toHex(getHeight())).append(" (").append(getHeight()).append(" )");
/*     */ 
/*     */     
/* 146 */     stringBuffer.append(System.getProperty("line.separator"));
/* 147 */     stringBuffer.append("    .options1             = ").append("0x").append(HexDump.toHex(getOptions1())).append(" (").append(getOptions1()).append(" )");
/*     */ 
/*     */     
/* 150 */     stringBuffer.append(System.getProperty("line.separator"));
/* 151 */     stringBuffer.append("         .autoColor                = ").append(isAutoColor()).append('\n');
/* 152 */     stringBuffer.append("         .showKey                  = ").append(isShowKey()).append('\n');
/* 153 */     stringBuffer.append("         .showValue                = ").append(isShowValue()).append('\n');
/* 154 */     stringBuffer.append("         .vertical                 = ").append(isVertical()).append('\n');
/* 155 */     stringBuffer.append("         .autoGeneratedText        = ").append(isAutoGeneratedText()).append('\n');
/* 156 */     stringBuffer.append("         .generated                = ").append(isGenerated()).append('\n');
/* 157 */     stringBuffer.append("         .autoLabelDeleted         = ").append(isAutoLabelDeleted()).append('\n');
/* 158 */     stringBuffer.append("         .autoBackground           = ").append(isAutoBackground()).append('\n');
/* 159 */     stringBuffer.append("         .rotation                 = ").append(getRotation()).append('\n');
/* 160 */     stringBuffer.append("         .showCategoryLabelAsPercentage     = ").append(isShowCategoryLabelAsPercentage()).append('\n');
/* 161 */     stringBuffer.append("         .showValueAsPercentage     = ").append(isShowValueAsPercentage()).append('\n');
/* 162 */     stringBuffer.append("         .showBubbleSizes          = ").append(isShowBubbleSizes()).append('\n');
/* 163 */     stringBuffer.append("         .showLabel                = ").append(isShowLabel()).append('\n');
/* 164 */     stringBuffer.append("    .indexOfColorValue    = ").append("0x").append(HexDump.toHex(getIndexOfColorValue())).append(" (").append(getIndexOfColorValue()).append(" )");
/*     */ 
/*     */     
/* 167 */     stringBuffer.append(System.getProperty("line.separator"));
/* 168 */     stringBuffer.append("    .options2             = ").append("0x").append(HexDump.toHex(getOptions2())).append(" (").append(getOptions2()).append(" )");
/*     */ 
/*     */     
/* 171 */     stringBuffer.append(System.getProperty("line.separator"));
/* 172 */     stringBuffer.append("         .dataLabelPlacement       = ").append(getDataLabelPlacement()).append('\n');
/* 173 */     stringBuffer.append("    .textRotation         = ").append("0x").append(HexDump.toHex(getTextRotation())).append(" (").append(getTextRotation()).append(" )");
/*     */ 
/*     */     
/* 176 */     stringBuffer.append(System.getProperty("line.separator"));
/*     */     
/* 178 */     stringBuffer.append("[/TEXT]\n");
/* 179 */     return stringBuffer.toString();
/*     */   }
/*     */   
/*     */   public void serialize(LittleEndianOutput paramLittleEndianOutput) {
/* 183 */     paramLittleEndianOutput.writeByte(this.field_1_horizontalAlignment);
/* 184 */     paramLittleEndianOutput.writeByte(this.field_2_verticalAlignment);
/* 185 */     paramLittleEndianOutput.writeShort(this.field_3_displayMode);
/* 186 */     paramLittleEndianOutput.writeInt(this.field_4_rgbColor);
/* 187 */     paramLittleEndianOutput.writeInt(this.field_5_x);
/* 188 */     paramLittleEndianOutput.writeInt(this.field_6_y);
/* 189 */     paramLittleEndianOutput.writeInt(this.field_7_width);
/* 190 */     paramLittleEndianOutput.writeInt(this.field_8_height);
/* 191 */     paramLittleEndianOutput.writeShort(this.field_9_options1);
/* 192 */     paramLittleEndianOutput.writeShort(this.field_10_indexOfColorValue);
/* 193 */     paramLittleEndianOutput.writeShort(this.field_11_options2);
/* 194 */     paramLittleEndianOutput.writeShort(this.field_12_textRotation);
/*     */   }
/*     */   
/*     */   protected int getDataSize() {
/* 198 */     return 32;
/*     */   }
/*     */ 
/*     */   
/*     */   public short getSid() {
/* 203 */     return 4133;
/*     */   }
/*     */   
/*     */   public Object clone() {
/* 207 */     TextRecord textRecord = new TextRecord();
/*     */     
/* 209 */     textRecord.field_1_horizontalAlignment = this.field_1_horizontalAlignment;
/* 210 */     textRecord.field_2_verticalAlignment = this.field_2_verticalAlignment;
/* 211 */     textRecord.field_3_displayMode = this.field_3_displayMode;
/* 212 */     textRecord.field_4_rgbColor = this.field_4_rgbColor;
/* 213 */     textRecord.field_5_x = this.field_5_x;
/* 214 */     textRecord.field_6_y = this.field_6_y;
/* 215 */     textRecord.field_7_width = this.field_7_width;
/* 216 */     textRecord.field_8_height = this.field_8_height;
/* 217 */     textRecord.field_9_options1 = this.field_9_options1;
/* 218 */     textRecord.field_10_indexOfColorValue = this.field_10_indexOfColorValue;
/* 219 */     textRecord.field_11_options2 = this.field_11_options2;
/* 220 */     textRecord.field_12_textRotation = this.field_12_textRotation;
/* 221 */     return textRecord;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public byte getHorizontalAlignment() {
/* 238 */     return this.field_1_horizontalAlignment;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setHorizontalAlignment(byte paramByte) {
/* 253 */     this.field_1_horizontalAlignment = paramByte;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public byte getVerticalAlignment() {
/* 267 */     return this.field_2_verticalAlignment;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setVerticalAlignment(byte paramByte) {
/* 282 */     this.field_2_verticalAlignment = paramByte;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public short getDisplayMode() {
/* 294 */     return this.field_3_displayMode;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setDisplayMode(short paramShort) {
/* 307 */     this.field_3_displayMode = paramShort;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int getRgbColor() {
/* 315 */     return this.field_4_rgbColor;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setRgbColor(int paramInt) {
/* 323 */     this.field_4_rgbColor = paramInt;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int getX() {
/* 331 */     return this.field_5_x;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setX(int paramInt) {
/* 339 */     this.field_5_x = paramInt;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int getY() {
/* 347 */     return this.field_6_y;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setY(int paramInt) {
/* 355 */     this.field_6_y = paramInt;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int getWidth() {
/* 363 */     return this.field_7_width;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setWidth(int paramInt) {
/* 371 */     this.field_7_width = paramInt;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int getHeight() {
/* 379 */     return this.field_8_height;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setHeight(int paramInt) {
/* 387 */     this.field_8_height = paramInt;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public short getOptions1() {
/* 395 */     return this.field_9_options1;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setOptions1(short paramShort) {
/* 403 */     this.field_9_options1 = paramShort;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public short getIndexOfColorValue() {
/* 411 */     return this.field_10_indexOfColorValue;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setIndexOfColorValue(short paramShort) {
/* 419 */     this.field_10_indexOfColorValue = paramShort;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public short getOptions2() {
/* 427 */     return this.field_11_options2;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setOptions2(short paramShort) {
/* 435 */     this.field_11_options2 = paramShort;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public short getTextRotation() {
/* 443 */     return this.field_12_textRotation;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setTextRotation(short paramShort) {
/* 451 */     this.field_12_textRotation = paramShort;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setAutoColor(boolean paramBoolean) {
/* 460 */     this.field_9_options1 = autoColor.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isAutoColor() {
/* 469 */     return autoColor.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setShowKey(boolean paramBoolean) {
/* 478 */     this.field_9_options1 = showKey.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isShowKey() {
/* 487 */     return showKey.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setShowValue(boolean paramBoolean) {
/* 496 */     this.field_9_options1 = showValue.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isShowValue() {
/* 505 */     return showValue.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setVertical(boolean paramBoolean) {
/* 514 */     this.field_9_options1 = vertical.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isVertical() {
/* 523 */     return vertical.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setAutoGeneratedText(boolean paramBoolean) {
/* 532 */     this.field_9_options1 = autoGeneratedText.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isAutoGeneratedText() {
/* 541 */     return autoGeneratedText.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setGenerated(boolean paramBoolean) {
/* 550 */     this.field_9_options1 = generated.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isGenerated() {
/* 559 */     return generated.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setAutoLabelDeleted(boolean paramBoolean) {
/* 568 */     this.field_9_options1 = autoLabelDeleted.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isAutoLabelDeleted() {
/* 577 */     return autoLabelDeleted.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setAutoBackground(boolean paramBoolean) {
/* 586 */     this.field_9_options1 = autoBackground.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isAutoBackground() {
/* 595 */     return autoBackground.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setRotation(short paramShort) {
/* 604 */     this.field_9_options1 = rotation.setShortValue(this.field_9_options1, paramShort);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public short getRotation() {
/* 613 */     return rotation.getShortValue(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setShowCategoryLabelAsPercentage(boolean paramBoolean) {
/* 622 */     this.field_9_options1 = showCategoryLabelAsPercentage.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isShowCategoryLabelAsPercentage() {
/* 631 */     return showCategoryLabelAsPercentage.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setShowValueAsPercentage(boolean paramBoolean) {
/* 640 */     this.field_9_options1 = showValueAsPercentage.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isShowValueAsPercentage() {
/* 649 */     return showValueAsPercentage.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setShowBubbleSizes(boolean paramBoolean) {
/* 658 */     this.field_9_options1 = showBubbleSizes.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isShowBubbleSizes() {
/* 667 */     return showBubbleSizes.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setShowLabel(boolean paramBoolean) {
/* 676 */     this.field_9_options1 = showLabel.setShortBoolean(this.field_9_options1, paramBoolean);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean isShowLabel() {
/* 685 */     return showLabel.isSet(this.field_9_options1);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public void setDataLabelPlacement(short paramShort) {
/* 694 */     this.field_11_options2 = dataLabelPlacement.setShortValue(this.field_11_options2, paramShort);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public short getDataLabelPlacement() {
/* 703 */     return dataLabelPlacement.getShortValue(this.field_11_options2);
/*     */   }
/*     */ }


/* Location:              C:\Arremate\Arremate.jar!\org\apache\poi\hssf\record\chart\TextRecord.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */