ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICENVIARLANCEVIRADAMINUTO BOOLEAN;
ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICCOBRIRLANCEVIRADAMINUTO BOOLEAN;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEENVIARLANCEVIRADAMINUTO BOOLEAN;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITECOBRIRLANCEVIRADAMINUTO BOOLEAN;