ALTER TABLE TBEMPRESA ADD COLUMN IF NOT EXISTS SSC BOOLEAN;
ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICICMS BOOLEAN DEFAULT false;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEEQUALIZACAO NUMERIC(15,4);