ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICARREDONDARCASASDECIMAIS SMALLINT DEFAULT 2;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEARREDONDARCASASDECIMAIS SMALLINT DEFAULT 2;
ALTER TABLE TBCONFIGURACAO ADD COLUMN IF NOT EXISTS CONARREDONDARCASASDECIMAIS SMALLINT DEFAULT 2;
ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICMODODEDISPUTA SMALLINT;
ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICMOMENTOENVIARLANCEABERTO BIGINT;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEMOMENTOENVIARLANCEABERTO BIGINT;
