ALTER TABLE TBCONFIGURACAO ADD COLUMN IF NOT EXISTS CONPERCENTUALDISPUTAMEEPP DECIMAL(15,4) DEFAULT 5.01;
ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICPERCENTUALDISPUTAMEEPP DECIMAL(15,4) DEFAULT 5.01;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEPERCENTUALDISPUTAMEEPP DECIMAL(15,4);