ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICTOPTRES BOOLEAN DEFAULT FALSE;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITETOPTRES BOOLEAN DEFAULT FALSE;

ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICMANTERDEZPORCENTOPRIMEIROLUGAR BOOLEAN DEFAULT FALSE;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEMANTERDEZPORCENTOPRIMEIROLUGAR BOOLEAN DEFAULT FALSE;

ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICPERCENTUALPRIMEIROLUGAR DECIMAL(15,4) DEFAULT 10;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEPERCENTUALPRIMEIROLUGAR DECIMAL(15,4) DEFAULT 10;

ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEVALORLANCEFECHADO DECIMAL(15,4);

ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICSEGUIRPRIMEIROCOLOCADO BOOLEAN DEFAULT FALSE;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITESEGUIRPRIMEIROCOLOCADO BOOLEAN DEFAULT FALSE;

ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICEXCLUIRCOMPETIDOR BOOLEAN DEFAULT FALSE;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEEXCLUIRCOMPETIDOR BOOLEAN DEFAULT FALSE;

ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICPOSICAOEXCLUIRCOMPETIDOR INTEGER DEFAULT 4;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEPOSICAOEXCLUIRCOMPETIDOR INTEGER DEFAULT 4;

ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICUNITARIO BOOLEAN;
