ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICMOMENTOENVIARLANCEFECHADO BIGINT;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEMOMENTOENVIARLANCEFECHADO BIGINT;

ALTER TABLE TBITEMLICITACAO ALTER COLUMN ITEQUANTIDADE decimal(15,4);