ALTER TABLE TBEMPRESA ADD COLUMN IF NOT EXISTS EMPPROFILE VARCHAR;
ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICPRECLOSINGTIME INTEGER;
ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICCLOSINGTIME INTEGER;