ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEUNIDADEMEDIDA VARCHAR;

CREATE TABLE IF NOT EXISTS PUBLIC.TBSESSIONID (
	SESSIONID VARCHAR NOT NULL,
    SESSIONIDDATE TIMESTAMP NOT NULL,
	CONSTRAINT SESSIONID_PK PRIMARY KEY (SESSIONID, SESSIONIDDATE)
);