ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICMODALIDADE INTEGER DEFAULT 0;
ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICLANCESDISPENSARESTANDO BOOLEAN;
ALTER TABLE TBLICITACAO ADD COLUMN IF NOT EXISTS LICMOMENTOENVIARLANCEDISPENSA BIGINT;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITELANCESDISPENSARESTANDO BOOLEAN;
ALTER TABLE TBITEMLICITACAO ADD COLUMN IF NOT EXISTS ITEMOMENTOENVIARLANCEDISPENSA BIGINT;