/*     */ package org.apache.poi.ddf;
/*     */ 
/*     */ import java.util.HashMap;
/*     */ import java.util.Map;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public final class EscherProperties
/*     */ {
/*     */   public static final short TRANSFORM__ROTATION = 4;
/*     */   public static final short PROTECTION__LOCKROTATION = 119;
/*     */   public static final short PROTECTION__LOCKASPECTRATIO = 120;
/*     */   public static final short PROTECTION__LOCKPOSITION = 121;
/*     */   public static final short PROTECTION__LOCKAGAINSTSELECT = 122;
/*     */   public static final short PROTECTION__LOCKCROPPING = 123;
/*     */   public static final short PROTECTION__LOCKVERTICES = 124;
/*     */   public static final short PROTECTION__LOCKTEXT = 125;
/*     */   public static final short PROTECTION__LOCKADJUSTHANDLES = 126;
/*     */   public static final short PROTECTION__LOCKAGAINSTGROUPING = 127;
/*     */   public static final short TEXT__TEXTID = 128;
/*     */   public static final short TEXT__TEXTLEFT = 129;
/*     */   public static final short TEXT__TEXTTOP = 130;
/*     */   public static final short TEXT__TEXTRIGHT = 131;
/*     */   public static final short TEXT__TEXTBOTTOM = 132;
/*     */   public static final short TEXT__WRAPTEXT = 133;
/*     */   public static final short TEXT__SCALETEXT = 134;
/*     */   public static final short TEXT__ANCHORTEXT = 135;
/*     */   public static final short TEXT__TEXTFLOW = 136;
/*     */   public static final short TEXT__FONTROTATION = 137;
/*     */   public static final short TEXT__IDOFNEXTSHAPE = 138;
/*     */   public static final short TEXT__BIDIR = 139;
/*     */   public static final short TEXT__SINGLECLICKSELECTS = 187;
/*     */   public static final short TEXT__USEHOSTMARGINS = 188;
/*     */   public static final short TEXT__ROTATETEXTWITHSHAPE = 189;
/*     */   public static final short TEXT__SIZESHAPETOFITTEXT = 190;
/*     */   public static final short TEXT__SIZE_TEXT_TO_FIT_SHAPE = 191;
/*     */   public static final short GEOTEXT__UNICODE = 192;
/*     */   public static final short GEOTEXT__RTFTEXT = 193;
/*     */   public static final short GEOTEXT__ALIGNMENTONCURVE = 194;
/*     */   public static final short GEOTEXT__DEFAULTPOINTSIZE = 195;
/*     */   public static final short GEOTEXT__TEXTSPACING = 196;
/*     */   public static final short GEOTEXT__FONTFAMILYNAME = 197;
/*     */   public static final short GEOTEXT__REVERSEROWORDER = 240;
/*     */   public static final short GEOTEXT__HASTEXTEFFECT = 241;
/*     */   public static final short GEOTEXT__ROTATECHARACTERS = 242;
/*     */   public static final short GEOTEXT__KERNCHARACTERS = 243;
/*     */   public static final short GEOTEXT__TIGHTORTRACK = 244;
/*     */   public static final short GEOTEXT__STRETCHTOFITSHAPE = 245;
/*     */   public static final short GEOTEXT__CHARBOUNDINGBOX = 246;
/*     */   public static final short GEOTEXT__SCALETEXTONPATH = 247;
/*     */   public static final short GEOTEXT__STRETCHCHARHEIGHT = 248;
/*     */   public static final short GEOTEXT__NOMEASUREALONGPATH = 249;
/*     */   public static final short GEOTEXT__BOLDFONT = 250;
/*     */   public static final short GEOTEXT__ITALICFONT = 251;
/*     */   public static final short GEOTEXT__UNDERLINEFONT = 252;
/*     */   public static final short GEOTEXT__SHADOWFONT = 253;
/*     */   public static final short GEOTEXT__SMALLCAPSFONT = 254;
/*     */   public static final short GEOTEXT__STRIKETHROUGHFONT = 255;
/*     */   public static final short BLIP__CROPFROMTOP = 256;
/*     */   public static final short BLIP__CROPFROMBOTTOM = 257;
/*     */   public static final short BLIP__CROPFROMLEFT = 258;
/*     */   public static final short BLIP__CROPFROMRIGHT = 259;
/*     */   public static final short BLIP__BLIPTODISPLAY = 260;
/*     */   public static final short BLIP__BLIPFILENAME = 261;
/*     */   public static final short BLIP__BLIPFLAGS = 262;
/*     */   public static final short BLIP__TRANSPARENTCOLOR = 263;
/*     */   public static final short BLIP__CONTRASTSETTING = 264;
/*     */   public static final short BLIP__BRIGHTNESSSETTING = 265;
/*     */   public static final short BLIP__GAMMA = 266;
/*     */   public static final short BLIP__PICTUREID = 267;
/*     */   public static final short BLIP__DOUBLEMOD = 268;
/*     */   public static final short BLIP__PICTUREFILLMOD = 269;
/*     */   public static final short BLIP__PICTURELINE = 270;
/*     */   public static final short BLIP__PRINTBLIP = 271;
/*     */   public static final short BLIP__PRINTBLIPFILENAME = 272;
/*     */   public static final short BLIP__PRINTFLAGS = 273;
/*     */   public static final short BLIP__NOHITTESTPICTURE = 316;
/*     */   public static final short BLIP__PICTUREGRAY = 317;
/*     */   public static final short BLIP__PICTUREBILEVEL = 318;
/*     */   public static final short BLIP__PICTUREACTIVE = 319;
/*     */   public static final short GEOMETRY__LEFT = 320;
/*     */   public static final short GEOMETRY__TOP = 321;
/*     */   public static final short GEOMETRY__RIGHT = 322;
/*     */   public static final short GEOMETRY__BOTTOM = 323;
/*     */   public static final short GEOMETRY__SHAPEPATH = 324;
/*     */   public static final short GEOMETRY__VERTICES = 325;
/*     */   public static final short GEOMETRY__SEGMENTINFO = 326;
/*     */   public static final short GEOMETRY__ADJUSTVALUE = 327;
/*     */   public static final short GEOMETRY__ADJUST2VALUE = 328;
/*     */   public static final short GEOMETRY__ADJUST3VALUE = 329;
/*     */   public static final short GEOMETRY__ADJUST4VALUE = 330;
/*     */   public static final short GEOMETRY__ADJUST5VALUE = 331;
/*     */   public static final short GEOMETRY__ADJUST6VALUE = 332;
/*     */   public static final short GEOMETRY__ADJUST7VALUE = 333;
/*     */   public static final short GEOMETRY__ADJUST8VALUE = 334;
/*     */   public static final short GEOMETRY__ADJUST9VALUE = 335;
/*     */   public static final short GEOMETRY__ADJUST10VALUE = 336;
/*     */   public static final short GEOMETRY__SHADOWok = 378;
/*     */   public static final short GEOMETRY__3DOK = 379;
/*     */   public static final short GEOMETRY__LINEOK = 380;
/*     */   public static final short GEOMETRY__GEOTEXTOK = 381;
/*     */   public static final short GEOMETRY__FILLSHADESHAPEOK = 382;
/*     */   public static final short GEOMETRY__FILLOK = 383;
/*     */   public static final short FILL__FILLTYPE = 384;
/*     */   public static final short FILL__FILLCOLOR = 385;
/*     */   public static final short FILL__FILLOPACITY = 386;
/*     */   public static final short FILL__FILLBACKCOLOR = 387;
/*     */   public static final short FILL__BACKOPACITY = 388;
/*     */   public static final short FILL__CRMOD = 389;
/*     */   public static final short FILL__PATTERNTEXTURE = 390;
/*     */   public static final short FILL__BLIPFILENAME = 391;
/*     */   public static final short FILL__BLIPFLAGS = 392;
/*     */   public static final short FILL__WIDTH = 393;
/*     */   public static final short FILL__HEIGHT = 394;
/*     */   public static final short FILL__ANGLE = 395;
/*     */   public static final short FILL__FOCUS = 396;
/*     */   public static final short FILL__TOLEFT = 397;
/*     */   public static final short FILL__TOTOP = 398;
/*     */   public static final short FILL__TORIGHT = 399;
/*     */   public static final short FILL__TOBOTTOM = 400;
/*     */   public static final short FILL__RECTLEFT = 401;
/*     */   public static final short FILL__RECTTOP = 402;
/*     */   public static final short FILL__RECTRIGHT = 403;
/*     */   public static final short FILL__RECTBOTTOM = 404;
/*     */   public static final short FILL__DZTYPE = 405;
/*     */   public static final short FILL__SHADEPRESET = 406;
/*     */   public static final short FILL__SHADECOLORS = 407;
/*     */   public static final short FILL__ORIGINX = 408;
/*     */   public static final short FILL__ORIGINY = 409;
/*     */   public static final short FILL__SHAPEORIGINX = 410;
/*     */   public static final short FILL__SHAPEORIGINY = 411;
/*     */   public static final short FILL__SHADETYPE = 412;
/*     */   public static final short FILL__FILLED = 443;
/*     */   public static final short FILL__HITTESTFILL = 444;
/*     */   public static final short FILL__SHAPE = 445;
/*     */   public static final short FILL__USERECT = 446;
/*     */   public static final short FILL__NOFILLHITTEST = 447;
/*     */   public static final short LINESTYLE__COLOR = 448;
/*     */   public static final short LINESTYLE__OPACITY = 449;
/*     */   public static final short LINESTYLE__BACKCOLOR = 450;
/*     */   public static final short LINESTYLE__CRMOD = 451;
/*     */   public static final short LINESTYLE__LINETYPE = 452;
/*     */   public static final short LINESTYLE__FILLBLIP = 453;
/*     */   public static final short LINESTYLE__FILLBLIPNAME = 454;
/*     */   public static final short LINESTYLE__FILLBLIPFLAGS = 455;
/*     */   public static final short LINESTYLE__FILLWIDTH = 456;
/*     */   public static final short LINESTYLE__FILLHEIGHT = 457;
/*     */   public static final short LINESTYLE__FILLDZTYPE = 458;
/*     */   public static final short LINESTYLE__LINEWIDTH = 459;
/*     */   public static final short LINESTYLE__LINEMITERLIMIT = 460;
/*     */   public static final short LINESTYLE__LINESTYLE = 461;
/*     */   public static final short LINESTYLE__LINEDASHING = 462;
/*     */   public static final short LINESTYLE__LINEDASHSTYLE = 463;
/*     */   public static final short LINESTYLE__LINESTARTARROWHEAD = 464;
/*     */   public static final short LINESTYLE__LINEENDARROWHEAD = 465;
/*     */   public static final short LINESTYLE__LINESTARTARROWWIDTH = 466;
/*     */   public static final short LINESTYLE__LINESTARTARROWLENGTH = 467;
/*     */   public static final short LINESTYLE__LINEENDARROWWIDTH = 468;
/*     */   public static final short LINESTYLE__LINEENDARROWLENGTH = 469;
/*     */   public static final short LINESTYLE__LINEJOINSTYLE = 470;
/*     */   public static final short LINESTYLE__LINEENDCAPSTYLE = 471;
/*     */   public static final short LINESTYLE__ARROWHEADSOK = 507;
/*     */   public static final short LINESTYLE__ANYLINE = 508;
/*     */   public static final short LINESTYLE__HITLINETEST = 509;
/*     */   public static final short LINESTYLE__LINEFILLSHAPE = 510;
/*     */   public static final short LINESTYLE__NOLINEDRAWDASH = 511;
/*     */   public static final short LINESTYLE__NOLINEDRAWDASH_LEFT = 1407;
/*     */   public static final short LINESTYLE__NOLINEDRAWDASH_TOP = 1471;
/*     */   public static final short LINESTYLE__NOLINEDRAWDASH_BOTTOM = 1599;
/*     */   public static final short LINESTYLE__NOLINEDRAWDASH_RIGHT = 1535;
/*     */   public static final short SHADOWSTYLE__TYPE = 512;
/*     */   public static final short SHADOWSTYLE__COLOR = 513;
/*     */   public static final short SHADOWSTYLE__HIGHLIGHT = 514;
/*     */   public static final short SHADOWSTYLE__CRMOD = 515;
/*     */   public static final short SHADOWSTYLE__OPACITY = 516;
/*     */   public static final short SHADOWSTYLE__OFFSETX = 517;
/*     */   public static final short SHADOWSTYLE__OFFSETY = 518;
/*     */   public static final short SHADOWSTYLE__SECONDOFFSETX = 519;
/*     */   public static final short SHADOWSTYLE__SECONDOFFSETY = 520;
/*     */   public static final short SHADOWSTYLE__SCALEXTOX = 521;
/*     */   public static final short SHADOWSTYLE__SCALEYTOX = 522;
/*     */   public static final short SHADOWSTYLE__SCALEXTOY = 523;
/*     */   public static final short SHADOWSTYLE__SCALEYTOY = 524;
/*     */   public static final short SHADOWSTYLE__PERSPECTIVEX = 525;
/*     */   public static final short SHADOWSTYLE__PERSPECTIVEY = 526;
/*     */   public static final short SHADOWSTYLE__WEIGHT = 527;
/*     */   public static final short SHADOWSTYLE__ORIGINX = 528;
/*     */   public static final short SHADOWSTYLE__ORIGINY = 529;
/*     */   public static final short SHADOWSTYLE__SHADOW = 574;
/*     */   public static final short SHADOWSTYLE__SHADOWOBSURED = 575;
/*     */   public static final short PERSPECTIVE__TYPE = 576;
/*     */   public static final short PERSPECTIVE__OFFSETX = 577;
/*     */   public static final short PERSPECTIVE__OFFSETY = 578;
/*     */   public static final short PERSPECTIVE__SCALEXTOX = 579;
/*     */   public static final short PERSPECTIVE__SCALEYTOX = 580;
/*     */   public static final short PERSPECTIVE__SCALEXTOY = 581;
/*     */   public static final short PERSPECTIVE__SCALEYTOY = 582;
/*     */   public static final short PERSPECTIVE__PERSPECTIVEX = 583;
/*     */   public static final short PERSPECTIVE__PERSPECTIVEY = 584;
/*     */   public static final short PERSPECTIVE__WEIGHT = 585;
/*     */   public static final short PERSPECTIVE__ORIGINX = 586;
/*     */   public static final short PERSPECTIVE__ORIGINY = 587;
/*     */   public static final short PERSPECTIVE__PERSPECTIVEON = 639;
/*     */   public static final short THREED__SPECULARAMOUNT = 640;
/*     */   public static final short THREED__DIFFUSEAMOUNT = 661;
/*     */   public static final short THREED__SHININESS = 662;
/*     */   public static final short THREED__EDGETHICKNESS = 663;
/*     */   public static final short THREED__EXTRUDEFORWARD = 664;
/*     */   public static final short THREED__EXTRUDEBACKWARD = 665;
/*     */   public static final short THREED__EXTRUDEPLANE = 666;
/*     */   public static final short THREED__EXTRUSIONCOLOR = 667;
/*     */   public static final short THREED__CRMOD = 648;
/*     */   public static final short THREED__3DEFFECT = 700;
/*     */   public static final short THREED__METALLIC = 701;
/*     */   public static final short THREED__USEEXTRUSIONCOLOR = 702;
/*     */   public static final short THREED__LIGHTFACE = 703;
/*     */   public static final short THREEDSTYLE__YROTATIONANGLE = 704;
/*     */   public static final short THREEDSTYLE__XROTATIONANGLE = 705;
/*     */   public static final short THREEDSTYLE__ROTATIONAXISX = 706;
/*     */   public static final short THREEDSTYLE__ROTATIONAXISY = 707;
/*     */   public static final short THREEDSTYLE__ROTATIONAXISZ = 708;
/*     */   public static final short THREEDSTYLE__ROTATIONANGLE = 709;
/*     */   public static final short THREEDSTYLE__ROTATIONCENTERX = 710;
/*     */   public static final short THREEDSTYLE__ROTATIONCENTERY = 711;
/*     */   public static final short THREEDSTYLE__ROTATIONCENTERZ = 712;
/*     */   public static final short THREEDSTYLE__RENDERMODE = 713;
/*     */   public static final short THREEDSTYLE__TOLERANCE = 714;
/*     */   public static final short THREEDSTYLE__XVIEWPOINT = 715;
/*     */   public static final short THREEDSTYLE__YVIEWPOINT = 716;
/*     */   public static final short THREEDSTYLE__ZVIEWPOINT = 717;
/*     */   public static final short THREEDSTYLE__ORIGINX = 718;
/*     */   public static final short THREEDSTYLE__ORIGINY = 719;
/*     */   public static final short THREEDSTYLE__SKEWANGLE = 720;
/*     */   public static final short THREEDSTYLE__SKEWAMOUNT = 721;
/*     */   public static final short THREEDSTYLE__AMBIENTINTENSITY = 722;
/*     */   public static final short THREEDSTYLE__KEYX = 723;
/*     */   public static final short THREEDSTYLE__KEYY = 724;
/*     */   public static final short THREEDSTYLE__KEYZ = 725;
/*     */   public static final short THREEDSTYLE__KEYINTENSITY = 726;
/*     */   public static final short THREEDSTYLE__FILLX = 727;
/*     */   public static final short THREEDSTYLE__FILLY = 728;
/*     */   public static final short THREEDSTYLE__FILLZ = 729;
/*     */   public static final short THREEDSTYLE__FILLINTENSITY = 730;
/*     */   public static final short THREEDSTYLE__CONSTRAINROTATION = 763;
/*     */   public static final short THREEDSTYLE__ROTATIONCENTERAUTO = 764;
/*     */   public static final short THREEDSTYLE__PARALLEL = 765;
/*     */   public static final short THREEDSTYLE__KEYHARSH = 766;
/*     */   public static final short THREEDSTYLE__FILLHARSH = 767;
/*     */   public static final short SHAPE__MASTER = 769;
/*     */   public static final short SHAPE__CONNECTORSTYLE = 771;
/*     */   public static final short SHAPE__BLACKANDWHITESETTINGS = 772;
/*     */   public static final short SHAPE__WMODEPUREBW = 773;
/*     */   public static final short SHAPE__WMODEBW = 774;
/*     */   public static final short SHAPE__OLEICON = 826;
/*     */   public static final short SHAPE__PREFERRELATIVERESIZE = 827;
/*     */   public static final short SHAPE__LOCKSHAPETYPE = 828;
/*     */   public static final short SHAPE__DELETEATTACHEDOBJECT = 830;
/*     */   public static final short SHAPE__BACKGROUNDSHAPE = 831;
/*     */   public static final short CALLOUT__CALLOUTTYPE = 832;
/*     */   public static final short CALLOUT__XYCALLOUTGAP = 833;
/*     */   public static final short CALLOUT__CALLOUTANGLE = 834;
/*     */   public static final short CALLOUT__CALLOUTDROPTYPE = 835;
/*     */   public static final short CALLOUT__CALLOUTDROPSPECIFIED = 836;
/*     */   public static final short CALLOUT__CALLOUTLENGTHSPECIFIED = 837;
/*     */   public static final short CALLOUT__ISCALLOUT = 889;
/*     */   public static final short CALLOUT__CALLOUTACCENTBAR = 890;
/*     */   public static final short CALLOUT__CALLOUTTEXTBORDER = 891;
/*     */   public static final short CALLOUT__CALLOUTMINUSX = 892;
/*     */   public static final short CALLOUT__CALLOUTMINUSY = 893;
/*     */   public static final short CALLOUT__DROPAUTO = 894;
/*     */   public static final short CALLOUT__LENGTHSPECIFIED = 895;
/*     */   public static final short GROUPSHAPE__SHAPENAME = 896;
/*     */   public static final short GROUPSHAPE__DESCRIPTION = 897;
/*     */   public static final short GROUPSHAPE__HYPERLINK = 898;
/*     */   public static final short GROUPSHAPE__WRAPPOLYGONVERTICES = 899;
/*     */   public static final short GROUPSHAPE__WRAPDISTLEFT = 900;
/*     */   public static final short GROUPSHAPE__WRAPDISTTOP = 901;
/*     */   public static final short GROUPSHAPE__WRAPDISTRIGHT = 902;
/*     */   public static final short GROUPSHAPE__WRAPDISTBOTTOM = 903;
/*     */   public static final short GROUPSHAPE__REGROUPID = 904;
/*     */   public static final short GROUPSHAPE__UNUSED906 = 906;
/*     */   public static final short GROUPSHAPE__TOOLTIP = 909;
/*     */   public static final short GROUPSHAPE__SCRIPT = 910;
/*     */   public static final short GROUPSHAPE__POSH = 911;
/*     */   public static final short GROUPSHAPE__POSRELH = 912;
/*     */   public static final short GROUPSHAPE__POSV = 913;
/*     */   public static final short GROUPSHAPE__POSRELV = 914;
/*     */   public static final short GROUPSHAPE__HR_PCT = 915;
/*     */   public static final short GROUPSHAPE__HR_ALIGN = 916;
/*     */   public static final short GROUPSHAPE__HR_HEIGHT = 917;
/*     */   public static final short GROUPSHAPE__HR_WIDTH = 918;
/*     */   public static final short GROUPSHAPE__SCRIPTEXT = 919;
/*     */   public static final short GROUPSHAPE__SCRIPTLANG = 920;
/*     */   public static final short GROUPSHAPE__BORDERTOPCOLOR = 923;
/*     */   public static final short GROUPSHAPE__BORDERLEFTCOLOR = 924;
/*     */   public static final short GROUPSHAPE__BORDERBOTTOMCOLOR = 925;
/*     */   public static final short GROUPSHAPE__BORDERRIGHTCOLOR = 926;
/*     */   public static final short GROUPSHAPE__TABLEPROPERTIES = 927;
/*     */   public static final short GROUPSHAPE__TABLEROWPROPERTIES = 928;
/*     */   public static final short GROUPSHAPE__WEBBOT = 933;
/*     */   public static final short GROUPSHAPE__METROBLOB = 937;
/*     */   public static final short GROUPSHAPE__ZORDER = 938;
/*     */   public static final short GROUPSHAPE__FLAGS = 959;
/*     */   public static final short GROUPSHAPE__EDITEDWRAP = 953;
/*     */   public static final short GROUPSHAPE__BEHINDDOCUMENT = 954;
/*     */   public static final short GROUPSHAPE__ONDBLCLICKNOTIFY = 955;
/*     */   public static final short GROUPSHAPE__ISBUTTON = 956;
/*     */   public static final short GROUPSHAPE__1DADJUSTMENT = 957;
/*     */   public static final short GROUPSHAPE__HIDDEN = 958;
/*     */   public static final short GROUPSHAPE__PRINT = 959;
/* 334 */   private static final Map<Short, EscherPropertyMetaData> properties = initProps();
/*     */   
/*     */   private static Map<Short, EscherPropertyMetaData> initProps() {
/* 337 */     HashMap<Object, Object> hashMap = new HashMap<Object, Object>();
/* 338 */     addProp((Map)hashMap, 4, "transform.rotation");
/* 339 */     addProp((Map)hashMap, 119, "protection.lockrotation");
/* 340 */     addProp((Map)hashMap, 120, "protection.lockaspectratio");
/* 341 */     addProp((Map)hashMap, 121, "protection.lockposition");
/* 342 */     addProp((Map)hashMap, 122, "protection.lockagainstselect");
/* 343 */     addProp((Map)hashMap, 123, "protection.lockcropping");
/* 344 */     addProp((Map)hashMap, 124, "protection.lockvertices");
/* 345 */     addProp((Map)hashMap, 125, "protection.locktext");
/* 346 */     addProp((Map)hashMap, 126, "protection.lockadjusthandles");
/* 347 */     addProp((Map)hashMap, 127, "protection.lockagainstgrouping", (byte)1);
/* 348 */     addProp((Map)hashMap, 128, "text.textid");
/* 349 */     addProp((Map)hashMap, 129, "text.textleft");
/* 350 */     addProp((Map)hashMap, 130, "text.texttop");
/* 351 */     addProp((Map)hashMap, 131, "text.textright");
/* 352 */     addProp((Map)hashMap, 132, "text.textbottom");
/* 353 */     addProp((Map)hashMap, 133, "text.wraptext");
/* 354 */     addProp((Map)hashMap, 134, "text.scaletext");
/* 355 */     addProp((Map)hashMap, 135, "text.anchortext");
/* 356 */     addProp((Map)hashMap, 136, "text.textflow");
/* 357 */     addProp((Map)hashMap, 137, "text.fontrotation");
/* 358 */     addProp((Map)hashMap, 138, "text.idofnextshape");
/* 359 */     addProp((Map)hashMap, 139, "text.bidir");
/* 360 */     addProp((Map)hashMap, 187, "text.singleclickselects");
/* 361 */     addProp((Map)hashMap, 188, "text.usehostmargins");
/* 362 */     addProp((Map)hashMap, 189, "text.rotatetextwithshape");
/* 363 */     addProp((Map)hashMap, 190, "text.sizeshapetofittext");
/* 364 */     addProp((Map)hashMap, 191, "text.sizetexttofitshape", (byte)1);
/* 365 */     addProp((Map)hashMap, 192, "geotext.unicode");
/* 366 */     addProp((Map)hashMap, 193, "geotext.rtftext");
/* 367 */     addProp((Map)hashMap, 194, "geotext.alignmentoncurve");
/* 368 */     addProp((Map)hashMap, 195, "geotext.defaultpointsize");
/* 369 */     addProp((Map)hashMap, 196, "geotext.textspacing");
/* 370 */     addProp((Map)hashMap, 197, "geotext.fontfamilyname");
/* 371 */     addProp((Map)hashMap, 240, "geotext.reverseroworder");
/* 372 */     addProp((Map)hashMap, 241, "geotext.hastexteffect");
/* 373 */     addProp((Map)hashMap, 242, "geotext.rotatecharacters");
/* 374 */     addProp((Map)hashMap, 243, "geotext.kerncharacters");
/* 375 */     addProp((Map)hashMap, 244, "geotext.tightortrack");
/* 376 */     addProp((Map)hashMap, 245, "geotext.stretchtofitshape");
/* 377 */     addProp((Map)hashMap, 246, "geotext.charboundingbox");
/* 378 */     addProp((Map)hashMap, 247, "geotext.scaletextonpath");
/* 379 */     addProp((Map)hashMap, 248, "geotext.stretchcharheight");
/* 380 */     addProp((Map)hashMap, 249, "geotext.nomeasurealongpath");
/* 381 */     addProp((Map)hashMap, 250, "geotext.boldfont");
/* 382 */     addProp((Map)hashMap, 251, "geotext.italicfont");
/* 383 */     addProp((Map)hashMap, 252, "geotext.underlinefont");
/* 384 */     addProp((Map)hashMap, 253, "geotext.shadowfont");
/* 385 */     addProp((Map)hashMap, 254, "geotext.smallcapsfont");
/* 386 */     addProp((Map)hashMap, 255, "geotext.strikethroughfont");
/* 387 */     addProp((Map)hashMap, 256, "blip.cropfromtop");
/* 388 */     addProp((Map)hashMap, 257, "blip.cropfrombottom");
/* 389 */     addProp((Map)hashMap, 258, "blip.cropfromleft");
/* 390 */     addProp((Map)hashMap, 259, "blip.cropfromright");
/* 391 */     addProp((Map)hashMap, 260, "blip.bliptodisplay");
/* 392 */     addProp((Map)hashMap, 261, "blip.blipfilename");
/* 393 */     addProp((Map)hashMap, 262, "blip.blipflags");
/* 394 */     addProp((Map)hashMap, 263, "blip.transparentcolor");
/* 395 */     addProp((Map)hashMap, 264, "blip.contrastsetting");
/* 396 */     addProp((Map)hashMap, 265, "blip.brightnesssetting");
/* 397 */     addProp((Map)hashMap, 266, "blip.gamma");
/* 398 */     addProp((Map)hashMap, 267, "blip.pictureid");
/* 399 */     addProp((Map)hashMap, 268, "blip.doublemod");
/* 400 */     addProp((Map)hashMap, 269, "blip.picturefillmod");
/* 401 */     addProp((Map)hashMap, 270, "blip.pictureline");
/* 402 */     addProp((Map)hashMap, 271, "blip.printblip");
/* 403 */     addProp((Map)hashMap, 272, "blip.printblipfilename");
/* 404 */     addProp((Map)hashMap, 273, "blip.printflags");
/* 405 */     addProp((Map)hashMap, 316, "blip.nohittestpicture");
/* 406 */     addProp((Map)hashMap, 317, "blip.picturegray");
/* 407 */     addProp((Map)hashMap, 318, "blip.picturebilevel");
/* 408 */     addProp((Map)hashMap, 319, "blip.pictureactive");
/* 409 */     addProp((Map)hashMap, 320, "geometry.left");
/* 410 */     addProp((Map)hashMap, 321, "geometry.top");
/* 411 */     addProp((Map)hashMap, 322, "geometry.right");
/* 412 */     addProp((Map)hashMap, 323, "geometry.bottom");
/* 413 */     addProp((Map)hashMap, 324, "geometry.shapepath", (byte)3);
/* 414 */     addProp((Map)hashMap, 325, "geometry.vertices", (byte)5);
/* 415 */     addProp((Map)hashMap, 326, "geometry.segmentinfo", (byte)5);
/* 416 */     addProp((Map)hashMap, 327, "geometry.adjustvalue");
/* 417 */     addProp((Map)hashMap, 328, "geometry.adjust2value");
/* 418 */     addProp((Map)hashMap, 329, "geometry.adjust3value");
/* 419 */     addProp((Map)hashMap, 330, "geometry.adjust4value");
/* 420 */     addProp((Map)hashMap, 331, "geometry.adjust5value");
/* 421 */     addProp((Map)hashMap, 332, "geometry.adjust6value");
/* 422 */     addProp((Map)hashMap, 333, "geometry.adjust7value");
/* 423 */     addProp((Map)hashMap, 334, "geometry.adjust8value");
/* 424 */     addProp((Map)hashMap, 335, "geometry.adjust9value");
/* 425 */     addProp((Map)hashMap, 336, "geometry.adjust10value");
/* 426 */     addProp((Map)hashMap, 378, "geometry.shadowOK");
/* 427 */     addProp((Map)hashMap, 379, "geometry.3dok");
/* 428 */     addProp((Map)hashMap, 380, "geometry.lineok");
/* 429 */     addProp((Map)hashMap, 381, "geometry.geotextok");
/* 430 */     addProp((Map)hashMap, 382, "geometry.fillshadeshapeok");
/* 431 */     addProp((Map)hashMap, 383, "geometry.fillok", (byte)1);
/* 432 */     addProp((Map)hashMap, 384, "fill.filltype");
/* 433 */     addProp((Map)hashMap, 385, "fill.fillcolor", (byte)2);
/* 434 */     addProp((Map)hashMap, 386, "fill.fillopacity");
/* 435 */     addProp((Map)hashMap, 387, "fill.fillbackcolor", (byte)2);
/* 436 */     addProp((Map)hashMap, 388, "fill.backopacity");
/* 437 */     addProp((Map)hashMap, 389, "fill.crmod");
/* 438 */     addProp((Map)hashMap, 390, "fill.patterntexture");
/* 439 */     addProp((Map)hashMap, 391, "fill.blipfilename");
/* 440 */     addProp((Map)hashMap, 392, "fill.blipflags");
/* 441 */     addProp((Map)hashMap, 393, "fill.width");
/* 442 */     addProp((Map)hashMap, 394, "fill.height");
/* 443 */     addProp((Map)hashMap, 395, "fill.angle");
/* 444 */     addProp((Map)hashMap, 396, "fill.focus");
/* 445 */     addProp((Map)hashMap, 397, "fill.toleft");
/* 446 */     addProp((Map)hashMap, 398, "fill.totop");
/* 447 */     addProp((Map)hashMap, 399, "fill.toright");
/* 448 */     addProp((Map)hashMap, 400, "fill.tobottom");
/* 449 */     addProp((Map)hashMap, 401, "fill.rectleft");
/* 450 */     addProp((Map)hashMap, 402, "fill.recttop");
/* 451 */     addProp((Map)hashMap, 403, "fill.rectright");
/* 452 */     addProp((Map)hashMap, 404, "fill.rectbottom");
/* 453 */     addProp((Map)hashMap, 405, "fill.dztype");
/* 454 */     addProp((Map)hashMap, 406, "fill.shadepreset");
/* 455 */     addProp((Map)hashMap, 407, "fill.shadecolors", (byte)5);
/* 456 */     addProp((Map)hashMap, 408, "fill.originx");
/* 457 */     addProp((Map)hashMap, 409, "fill.originy");
/* 458 */     addProp((Map)hashMap, 410, "fill.shapeoriginx");
/* 459 */     addProp((Map)hashMap, 411, "fill.shapeoriginy");
/* 460 */     addProp((Map)hashMap, 412, "fill.shadetype");
/* 461 */     addProp((Map)hashMap, 443, "fill.filled");
/* 462 */     addProp((Map)hashMap, 444, "fill.hittestfill");
/* 463 */     addProp((Map)hashMap, 445, "fill.shape");
/* 464 */     addProp((Map)hashMap, 446, "fill.userect");
/* 465 */     addProp((Map)hashMap, 447, "fill.nofillhittest", (byte)1);
/* 466 */     addProp((Map)hashMap, 448, "linestyle.color", (byte)2);
/* 467 */     addProp((Map)hashMap, 449, "linestyle.opacity");
/* 468 */     addProp((Map)hashMap, 450, "linestyle.backcolor", (byte)2);
/* 469 */     addProp((Map)hashMap, 451, "linestyle.crmod");
/* 470 */     addProp((Map)hashMap, 452, "linestyle.linetype");
/* 471 */     addProp((Map)hashMap, 453, "linestyle.fillblip");
/* 472 */     addProp((Map)hashMap, 454, "linestyle.fillblipname");
/* 473 */     addProp((Map)hashMap, 455, "linestyle.fillblipflags");
/* 474 */     addProp((Map)hashMap, 456, "linestyle.fillwidth");
/* 475 */     addProp((Map)hashMap, 457, "linestyle.fillheight");
/* 476 */     addProp((Map)hashMap, 458, "linestyle.filldztype");
/* 477 */     addProp((Map)hashMap, 459, "linestyle.linewidth");
/* 478 */     addProp((Map)hashMap, 460, "linestyle.linemiterlimit");
/* 479 */     addProp((Map)hashMap, 461, "linestyle.linestyle");
/* 480 */     addProp((Map)hashMap, 462, "linestyle.linedashing");
/* 481 */     addProp((Map)hashMap, 463, "linestyle.linedashstyle", (byte)5);
/* 482 */     addProp((Map)hashMap, 464, "linestyle.linestartarrowhead");
/* 483 */     addProp((Map)hashMap, 465, "linestyle.lineendarrowhead");
/* 484 */     addProp((Map)hashMap, 466, "linestyle.linestartarrowwidth");
/* 485 */     addProp((Map)hashMap, 467, "linestyle.linestartarrowlength");
/* 486 */     addProp((Map)hashMap, 468, "linestyle.lineendarrowwidth");
/* 487 */     addProp((Map)hashMap, 469, "linestyle.lineendarrowlength");
/* 488 */     addProp((Map)hashMap, 470, "linestyle.linejoinstyle");
/* 489 */     addProp((Map)hashMap, 471, "linestyle.lineendcapstyle");
/* 490 */     addProp((Map)hashMap, 507, "linestyle.arrowheadsok");
/* 491 */     addProp((Map)hashMap, 508, "linestyle.anyline");
/* 492 */     addProp((Map)hashMap, 509, "linestyle.hitlinetest");
/* 493 */     addProp((Map)hashMap, 510, "linestyle.linefillshape");
/* 494 */     addProp((Map)hashMap, 511, "linestyle.nolinedrawdash", (byte)1);
/* 495 */     addProp((Map)hashMap, 1407, "linestyle.nolinedrawdash.left", (byte)1);
/* 496 */     addProp((Map)hashMap, 1471, "linestyle.nolinedrawdash.top", (byte)1);
/* 497 */     addProp((Map)hashMap, 1599, "linestyle.nolinedrawdash.bottom", (byte)1);
/* 498 */     addProp((Map)hashMap, 1535, "linestyle.nolinedrawdash.right", (byte)1);
/* 499 */     addProp((Map)hashMap, 512, "shadowstyle.type");
/* 500 */     addProp((Map)hashMap, 513, "shadowstyle.color", (byte)2);
/* 501 */     addProp((Map)hashMap, 514, "shadowstyle.highlight");
/* 502 */     addProp((Map)hashMap, 515, "shadowstyle.crmod");
/* 503 */     addProp((Map)hashMap, 516, "shadowstyle.opacity");
/* 504 */     addProp((Map)hashMap, 517, "shadowstyle.offsetx");
/* 505 */     addProp((Map)hashMap, 518, "shadowstyle.offsety");
/* 506 */     addProp((Map)hashMap, 519, "shadowstyle.secondoffsetx");
/* 507 */     addProp((Map)hashMap, 520, "shadowstyle.secondoffsety");
/* 508 */     addProp((Map)hashMap, 521, "shadowstyle.scalextox");
/* 509 */     addProp((Map)hashMap, 522, "shadowstyle.scaleytox");
/* 510 */     addProp((Map)hashMap, 523, "shadowstyle.scalextoy");
/* 511 */     addProp((Map)hashMap, 524, "shadowstyle.scaleytoy");
/* 512 */     addProp((Map)hashMap, 525, "shadowstyle.perspectivex");
/* 513 */     addProp((Map)hashMap, 526, "shadowstyle.perspectivey");
/* 514 */     addProp((Map)hashMap, 527, "shadowstyle.weight");
/* 515 */     addProp((Map)hashMap, 528, "shadowstyle.originx");
/* 516 */     addProp((Map)hashMap, 529, "shadowstyle.originy");
/* 517 */     addProp((Map)hashMap, 574, "shadowstyle.shadow");
/* 518 */     addProp((Map)hashMap, 575, "shadowstyle.shadowobscured");
/* 519 */     addProp((Map)hashMap, 576, "perspective.type");
/* 520 */     addProp((Map)hashMap, 577, "perspective.offsetx");
/* 521 */     addProp((Map)hashMap, 578, "perspective.offsety");
/* 522 */     addProp((Map)hashMap, 579, "perspective.scalextox");
/* 523 */     addProp((Map)hashMap, 580, "perspective.scaleytox");
/* 524 */     addProp((Map)hashMap, 581, "perspective.scalextoy");
/* 525 */     addProp((Map)hashMap, 582, "perspective.scaleytoy");
/* 526 */     addProp((Map)hashMap, 583, "perspective.perspectivex");
/* 527 */     addProp((Map)hashMap, 584, "perspective.perspectivey");
/* 528 */     addProp((Map)hashMap, 585, "perspective.weight");
/* 529 */     addProp((Map)hashMap, 586, "perspective.originx");
/* 530 */     addProp((Map)hashMap, 587, "perspective.originy");
/* 531 */     addProp((Map)hashMap, 639, "perspective.perspectiveon");
/* 532 */     addProp((Map)hashMap, 640, "3d.specularamount");
/* 533 */     addProp((Map)hashMap, 661, "3d.diffuseamount");
/* 534 */     addProp((Map)hashMap, 662, "3d.shininess");
/* 535 */     addProp((Map)hashMap, 663, "3d.edgethickness");
/* 536 */     addProp((Map)hashMap, 664, "3d.extrudeforward");
/* 537 */     addProp((Map)hashMap, 665, "3d.extrudebackward");
/* 538 */     addProp((Map)hashMap, 666, "3d.extrudeplane");
/* 539 */     addProp((Map)hashMap, 667, "3d.extrusioncolor", (byte)2);
/* 540 */     addProp((Map)hashMap, 648, "3d.crmod");
/* 541 */     addProp((Map)hashMap, 700, "3d.3deffect");
/* 542 */     addProp((Map)hashMap, 701, "3d.metallic");
/* 543 */     addProp((Map)hashMap, 702, "3d.useextrusioncolor", (byte)2);
/* 544 */     addProp((Map)hashMap, 703, "3d.lightface");
/* 545 */     addProp((Map)hashMap, 704, "3dstyle.yrotationangle");
/* 546 */     addProp((Map)hashMap, 705, "3dstyle.xrotationangle");
/* 547 */     addProp((Map)hashMap, 706, "3dstyle.rotationaxisx");
/* 548 */     addProp((Map)hashMap, 707, "3dstyle.rotationaxisy");
/* 549 */     addProp((Map)hashMap, 708, "3dstyle.rotationaxisz");
/* 550 */     addProp((Map)hashMap, 709, "3dstyle.rotationangle");
/* 551 */     addProp((Map)hashMap, 710, "3dstyle.rotationcenterx");
/* 552 */     addProp((Map)hashMap, 711, "3dstyle.rotationcentery");
/* 553 */     addProp((Map)hashMap, 712, "3dstyle.rotationcenterz");
/* 554 */     addProp((Map)hashMap, 713, "3dstyle.rendermode");
/* 555 */     addProp((Map)hashMap, 714, "3dstyle.tolerance");
/* 556 */     addProp((Map)hashMap, 715, "3dstyle.xviewpoint");
/* 557 */     addProp((Map)hashMap, 716, "3dstyle.yviewpoint");
/* 558 */     addProp((Map)hashMap, 717, "3dstyle.zviewpoint");
/* 559 */     addProp((Map)hashMap, 718, "3dstyle.originx");
/* 560 */     addProp((Map)hashMap, 719, "3dstyle.originy");
/* 561 */     addProp((Map)hashMap, 720, "3dstyle.skewangle");
/* 562 */     addProp((Map)hashMap, 721, "3dstyle.skewamount");
/* 563 */     addProp((Map)hashMap, 722, "3dstyle.ambientintensity");
/* 564 */     addProp((Map)hashMap, 723, "3dstyle.keyx");
/* 565 */     addProp((Map)hashMap, 724, "3dstyle.keyy");
/* 566 */     addProp((Map)hashMap, 725, "3dstyle.keyz");
/* 567 */     addProp((Map)hashMap, 726, "3dstyle.keyintensity");
/* 568 */     addProp((Map)hashMap, 727, "3dstyle.fillx");
/* 569 */     addProp((Map)hashMap, 728, "3dstyle.filly");
/* 570 */     addProp((Map)hashMap, 729, "3dstyle.fillz");
/* 571 */     addProp((Map)hashMap, 730, "3dstyle.fillintensity");
/* 572 */     addProp((Map)hashMap, 763, "3dstyle.constrainrotation");
/* 573 */     addProp((Map)hashMap, 764, "3dstyle.rotationcenterauto");
/* 574 */     addProp((Map)hashMap, 765, "3dstyle.parallel");
/* 575 */     addProp((Map)hashMap, 766, "3dstyle.keyharsh");
/* 576 */     addProp((Map)hashMap, 767, "3dstyle.fillharsh");
/* 577 */     addProp((Map)hashMap, 769, "shape.master");
/* 578 */     addProp((Map)hashMap, 771, "shape.connectorstyle");
/* 579 */     addProp((Map)hashMap, 772, "shape.blackandwhitesettings");
/* 580 */     addProp((Map)hashMap, 773, "shape.wmodepurebw");
/* 581 */     addProp((Map)hashMap, 774, "shape.wmodebw");
/* 582 */     addProp((Map)hashMap, 826, "shape.oleicon");
/* 583 */     addProp((Map)hashMap, 827, "shape.preferrelativeresize");
/* 584 */     addProp((Map)hashMap, 828, "shape.lockshapetype");
/* 585 */     addProp((Map)hashMap, 830, "shape.deleteattachedobject");
/* 586 */     addProp((Map)hashMap, 831, "shape.backgroundshape");
/* 587 */     addProp((Map)hashMap, 832, "callout.callouttype");
/* 588 */     addProp((Map)hashMap, 833, "callout.xycalloutgap");
/* 589 */     addProp((Map)hashMap, 834, "callout.calloutangle");
/* 590 */     addProp((Map)hashMap, 835, "callout.calloutdroptype");
/* 591 */     addProp((Map)hashMap, 836, "callout.calloutdropspecified");
/* 592 */     addProp((Map)hashMap, 837, "callout.calloutlengthspecified");
/* 593 */     addProp((Map)hashMap, 889, "callout.iscallout");
/* 594 */     addProp((Map)hashMap, 890, "callout.calloutaccentbar");
/* 595 */     addProp((Map)hashMap, 891, "callout.callouttextborder");
/* 596 */     addProp((Map)hashMap, 892, "callout.calloutminusx");
/* 597 */     addProp((Map)hashMap, 893, "callout.calloutminusy");
/* 598 */     addProp((Map)hashMap, 894, "callout.dropauto");
/* 599 */     addProp((Map)hashMap, 895, "callout.lengthspecified");
/* 600 */     addProp((Map)hashMap, 896, "groupshape.shapename");
/* 601 */     addProp((Map)hashMap, 897, "groupshape.description");
/* 602 */     addProp((Map)hashMap, 898, "groupshape.hyperlink");
/* 603 */     addProp((Map)hashMap, 899, "groupshape.wrappolygonvertices", (byte)5);
/* 604 */     addProp((Map)hashMap, 900, "groupshape.wrapdistleft");
/* 605 */     addProp((Map)hashMap, 901, "groupshape.wrapdisttop");
/* 606 */     addProp((Map)hashMap, 902, "groupshape.wrapdistright");
/* 607 */     addProp((Map)hashMap, 903, "groupshape.wrapdistbottom");
/* 608 */     addProp((Map)hashMap, 904, "groupshape.regroupid");
/* 609 */     addProp((Map)hashMap, 906, "unused906");
/* 610 */     addProp((Map)hashMap, 909, "groupshape.wzTooltip");
/* 611 */     addProp((Map)hashMap, 910, "groupshape.wzScript");
/* 612 */     addProp((Map)hashMap, 911, "groupshape.posh");
/* 613 */     addProp((Map)hashMap, 912, "groupshape.posrelh");
/* 614 */     addProp((Map)hashMap, 913, "groupshape.posv");
/* 615 */     addProp((Map)hashMap, 914, "groupshape.posrelv");
/* 616 */     addProp((Map)hashMap, 915, "groupshape.pctHR");
/* 617 */     addProp((Map)hashMap, 916, "groupshape.alignHR");
/* 618 */     addProp((Map)hashMap, 917, "groupshape.dxHeightHR");
/* 619 */     addProp((Map)hashMap, 918, "groupshape.dxWidthHR");
/* 620 */     addProp((Map)hashMap, 919, "groupshape.wzScriptExtAttr");
/* 621 */     addProp((Map)hashMap, 920, "groupshape.scriptLang");
/* 622 */     addProp((Map)hashMap, 923, "groupshape.borderTopColor");
/* 623 */     addProp((Map)hashMap, 924, "groupshape.borderLeftColor");
/* 624 */     addProp((Map)hashMap, 925, "groupshape.borderBottomColor");
/* 625 */     addProp((Map)hashMap, 926, "groupshape.borderRightColor");
/* 626 */     addProp((Map)hashMap, 927, "groupshape.tableProperties");
/* 627 */     addProp((Map)hashMap, 928, "groupshape.tableRowProperties");
/* 628 */     addProp((Map)hashMap, 933, "groupshape.wzWebBot");
/* 629 */     addProp((Map)hashMap, 937, "groupshape.metroBlob");
/* 630 */     addProp((Map)hashMap, 938, "groupshape.dhgt");
/* 631 */     addProp((Map)hashMap, 959, "groupshape.GroupShapeBooleanProperties");
/*     */     
/* 633 */     addProp((Map)hashMap, 953, "groupshape.editedwrap");
/* 634 */     addProp((Map)hashMap, 954, "groupshape.behinddocument");
/* 635 */     addProp((Map)hashMap, 955, "groupshape.ondblclicknotify");
/* 636 */     addProp((Map)hashMap, 956, "groupshape.isbutton");
/* 637 */     addProp((Map)hashMap, 957, "groupshape.1dadjustment");
/* 638 */     addProp((Map)hashMap, 958, "groupshape.hidden");
/* 639 */     addProp((Map)hashMap, 959, "groupshape.print", (byte)1);
/* 640 */     return (Map)hashMap;
/*     */   }
/*     */   
/*     */   private static void addProp(Map<Short, EscherPropertyMetaData> paramMap, int paramInt, String paramString) {
/* 644 */     paramMap.put(Short.valueOf((short)paramInt), new EscherPropertyMetaData(paramString));
/*     */   }
/*     */   
/*     */   private static void addProp(Map<Short, EscherPropertyMetaData> paramMap, int paramInt, String paramString, byte paramByte) {
/* 648 */     paramMap.put(Short.valueOf((short)paramInt), new EscherPropertyMetaData(paramString, paramByte));
/*     */   }
/*     */   
/*     */   public static String getPropertyName(short paramShort) {
/* 652 */     EscherPropertyMetaData escherPropertyMetaData = properties.get(Short.valueOf(paramShort));
/* 653 */     return (escherPropertyMetaData == null) ? "unknown" : escherPropertyMetaData.getDescription();
/*     */   }
/*     */   
/*     */   public static byte getPropertyType(short paramShort) {
/* 657 */     EscherPropertyMetaData escherPropertyMetaData = properties.get(Short.valueOf(paramShort));
/* 658 */     return (escherPropertyMetaData == null) ? 0 : escherPropertyMetaData.getType();
/*     */   }
/*     */ }


/* Location:              C:\Arremate\Arremate.jar!\org\apache\poi\ddf\EscherProperties.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */